var networksSpecific = {"Specific NNSA with Recommendations(1)": {
  "format_version" : "1.0",
  "generated_by" : "cytoscape-3.10.3",
  "target_cytoscapejs_version" : "~2.1",
  "data" : {
    "shared_name" : "Specific NNSA with Recommendations(1)",
    "name" : "Specific NNSA with Recommendations(1)",
    "SUID" : 16022,
    "__Annotations" : [ ],
    "selected" : true
  },
  "elements" : {
    "nodes" : [ {
      "data" : {
        "id" : "8232",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "Renumbers BOP-06.05, Project Management for the Acquisition of Capital Assets, dated 8-9-2016.",
        "LastUpdate" : "",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "Office of Enterprise Project Management",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://directives.nnsa.doe.gov/bop/bop-0413-007",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Acquisition & Project Management",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8232,
        "ID" : "BOP 413.7",
        "TabRelatedTo" : "NULL",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1225,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "9-Aug-16",
        "DNFSB" : "No",
        "Title1" : "Project Management for the Acquisition of Capital Assets",
        "PDFDocName" : "BOP 413.7.pdf",
        "CTA" : "No",
        "Type" : "Business Operating Procedure (BOP)",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/bop/bop-0413-007",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/bop/bop-0413-007/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -4366.5416289075565,
        "y" : -630.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8192",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "To establish the requirements, processes, and procedures for conducting biennial reviews (BRs) under the National Nuclear Security Administration (NNSA) Chief of Defense Nuclear Safety (CDNS).",
        "MiscComments" : "",
        "LastUpdate" : "26-Oct-20",
        "TabHistorySupersedes" : "[]",
        "TabHistorySupersededBy" : "[]",
        "OPI" : "Office of Safety, Infrastructure and Operations",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a\"      ]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Safety, Infrastructure and Operations",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8192,
        "ID" : "SD 226.1-1B",
        "TabRelatedTo" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b\"      ]",
        "NNSA_Related" : true,
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Current",
        "Nr" : 26,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "1",
        "IssueDate" : "26-Oct-20",
        "DNFSB" : "No",
        "Title1" : "Headquarters Biennial Review of Nuclear Safety Performance",
        "PDFDocName" : "SD 226.1-1B.pdf",
        "CTA" : "No",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b\",        \"https://www.directives.doe.gov/directives-documents/200-series/0226.2-APolicy\"      ]",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3661.622184463112,
        "y" : -1155.080127572864
      },
      "selected" : true
    }, {
      "data" : {
        "id" : "8230",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "The purpose of this Supplemental Directive (SD) is to implement Department of Energy (DOE) Order (O) 251.1D, Departmental Directives Program, and to define the formal system to set, communicate, and institutionalize directives (requirements, responsibilities, and procedures) specific to the National Nuclear Security Administration (NNSA).",
        "MiscComments" : "",
        "LastUpdate" : "",
        "TabHistorySupersedes" : "[]",
        "TabHistorySupersededBy" : "[]",
        "OPI" : "Office of Business Services",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-adm-chg-1\"      ]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-b\"      ]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Management & Budget",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8230,
        "ID" : "SD 251.1A",
        "TabRelatedTo" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b\"      ]",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 39,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "17-Jan-18",
        "DNFSB" : "Yes",
        "Title1" : "Directives Management",
        "PDFDocName" : "SD 251.1A.pdf",
        "CTA" : "Yes",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[]",
        "CRD" : "Yes",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3618.497184463112,
        "y" : -630.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8166",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "This Supplemental Directive (SD) establishes the National Nuclear Security Administration (NNSA) Site Governance Model as the framework that the Federal Government and NNSA’s contractor partners work within to help ensure effective mission performance and operational excellence. This SD supplements the requirements of Department of Energy (DOE) Policy (P) 226.2, Department of Energy Oversight Policy, and DOE Order (O) 226.1B, Implementation of DOE Oversight Policy.",
        "MiscComments" : "Supersedes SD 226.1B, NNSA Site Governance, dated 8-12-2016. Cancels BOP-10.003, Site Integrated Assessment Plan (SIAP) Development, Updating, and Reporting, dated 1-18-2012 and Unnumbered NA-50 document, Approach to Safety Management Plan Reviews, dated 5-22-2015.",
        "LastUpdate" : "1-Oct-19",
        "TabHistorySupersedes" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b\"      ]",
        "TabHistorySupersededBy" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d\"      ]",
        "OPI" : "Office of Safety, Infrastructure and Operations",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[        \"https://directives.nnsa.doe.gov/bop/bop-0010-0003\"      ]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Management & Budget",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8166,
        "ID" : "SD 226.1C",
        "TabRelatedTo" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002\",        \"https://directives.nnsa.doe.gov/bop/bop-0413-007\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/100-series/nap-0130-001\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0205-0001a\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b\"      ]",
        "NNSA_Related" : true,
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 30,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "1",
        "IssueDate" : "1-Oct-19",
        "DNFSB" : "No",
        "Title1" : "NNSA Site Governance",
        "PDFDocName" : "SD 226.1C.pdf",
        "CTA" : "No",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[        \"https://www.directives.doe.gov/directives-documents/200-series/0226.2-APolicy\",        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b\",        \"https://www.directives.doe.gov/directives-documents/200-series/0227.1-BOrder-A\",        \"https://www.directives.doe.gov/directives-documents/200-series/0251.001-BOrder-d\",        \"https://www.directives.doe.gov/directives-documents/400-series/0412.1-BOrder-a-chg1-AdmChg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-B-chg5-minchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0414.1-BOrder-d-admchg1\"      ]",
        "CRD" : "Yes",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3792.3023431932706,
        "y" : -890.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8242",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "This Supplemental Directive (SD) establishes the National Nuclear Security Administration (NNSA) Site Governance Model as the framework for site assurance and oversight that the Federal Government and NNSA’s Management and Operating (M&O) contractors work within to help ensure effective mission performance and operational excellence. This SD supplements the requirements of Department of Energy (DOE) Policy (P) 226.2, Department of Energy Oversight Policy, and DOE Order (O) 226.1B Change 1, Implementation of DOE Oversight Policy.",
        "MiscComments" : "",
        "LastUpdate" : "5-Dec-24",
        "TabHistorySupersedes" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-001-2\"      ]",
        "TabHistorySupersededBy" : "[]",
        "OPI" : "Office of the Principal Deputy Administrator",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of the Principal Deputy Administrator",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8242,
        "ID" : "SD 226.1D",
        "TabRelatedTo" : "[]",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Current",
        "Nr" : 91,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "5-Dec-24",
        "DNFSB" : "No",
        "Title1" : "NNSA Site Assurance and Oversight",
        "PDFDocName" : "SD_226.1D.pdf",
        "CTA" : "No",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[        \"https://www.directives.doe.gov/directives-documents/200-series/0226.2-APolicy\",        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b-chg1-admchg\"      ]",
        "CRD" : "Yes",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -4471.5416289075565,
        "y" : -630.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8370",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "Renumbers BOP-06.04, Project Reviews, dated 11-18-2014.",
        "LastUpdate" : "18-Nov-14",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "Office of Project Management and Systems Support",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://directives.nnsa.doe.gov/bop/bop-0413-004",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Acquisition & Project Management",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8370,
        "ID" : "BOP 413.4",
        "TabRelatedTo" : "NULL",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1220,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "18-Nov-14",
        "DNFSB" : "No",
        "Title1" : "Project Reviews",
        "PDFDocName" : "BOP 413.4.pdf",
        "CTA" : "No",
        "Type" : "Business Operating Procedure (BOP)",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/bop/bop-0413-004",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/bop/bop-0413-004/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3381.7983749393024,
        "y" : -275.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8216",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "",
        "LastUpdate" : "4-Feb-19",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "Office of System Engineering & Integration",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Defense Programs",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8216,
        "ID" : "NAP 413.2",
        "TabRelatedTo" : "NULL",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1245,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "4-Feb-19",
        "DNFSB" : "No",
        "Title1" : "Program Management Policy",
        "PDFDocName" : "NAP 413.2.pdf",
        "CTA" : "No",
        "Type" : "NNSA Policy (NAP)",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -4400.2916289075565,
        "y" : -275.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8164",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "This Supplemental Directive (SD) defines the authorities, requirements, and responsibilities for the cybersecurity of information technology (IT), including national security systems (NSS), information systems, and operational technology (OT) within the National Nuclear Security Administration (NNSA). This SD supplements Department of Energy (DOE) Order (O) 205.1D, Department of Energy Cybersecurity Program, and incorporates the principles, processes, and oversight requirements in SD 226.1, NNSA Site Assurance and Oversight, current version, and is consistent with executive and Federal authorities.",
        "MiscComments" : "",
        "LastUpdate" : "24-Sep-24",
        "TabHistorySupersedes" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0205-0001\"      ]",
        "TabHistorySupersededBy" : "[]",
        "OPI" : "Office of Chief Information Officer",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0205-0001a",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of the Associate Administrator Information Management and Chief Information Officer",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8164,
        "ID" : "SD 205.1A",
        "TabRelatedTo" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c\"      ]",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Current",
        "Nr" : 89,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "24-Sep-24",
        "DNFSB" : "No",
        "Title1" : "Baseline Cybersecurity Program",
        "PDFDocName" : "SD_205.1A.pdf",
        "CTA" : "No",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[        \"https://www.directives.doe.gov/directives-documents/200-series/0205-1-border-d\"      ]",
        "CRD" : "Yes",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0205-0001a",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0205-0001a/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3841.5416289075565,
        "y" : -630.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8240",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "NULL",
        "LastUpdate" : "12-Apr-18",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "NULL",
        "IS_DOE" : "Y",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-B-chg5-minchg",
        "OPR" : "PM - Office of Project Management Oversight and Assessments",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "Yes",
        "TabExemptions" : "NULL",
        "SLMOffice" : "NULL",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8240,
        "ID" : "DOE O 413.3B Chg 5 (MinChg)",
        "TabRelatedTo" : "NULL",
        "Subjects" : "Administration,Safety",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1560,
        "ApprovedDate" : "29-Nov-10",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "NULL",
        "DNFSB" : "NULL",
        "Title1" : "Program and Project Management for the Acquisition of Capital Assets",
        "PDFDocName" : "413.3Bchg5-minchg.pdf",
        "CTA" : "NULL",
        "Type" : "Order",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "Yes",
        "name" : "https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-B-chg5-minchg",
        "PDFDocLink" : "https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-B-chg5-minchg/@@images/file",
        "Writer" : "MFrank"
      },
      "position" : {
        "x" : -4261.5416289075565,
        "y" : -630.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8380",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "NULL",
        "LastUpdate" : "12-Jan-21",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "NULL",
        "IS_DOE" : "Y",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg6-ltdchg",
        "OPR" : "PM - Office of Project Management Oversight and Assessments",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "Yes",
        "TabExemptions" : "NULL",
        "SLMOffice" : "NULL",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8380,
        "ID" : "DOE O 413.3B Chg 6 (LtdChg)",
        "TabRelatedTo" : "NULL",
        "Subjects" : "Administration,Safety",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1561,
        "ApprovedDate" : "29-Nov-10",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "NULL",
        "DNFSB" : "NULL",
        "Title1" : "Program and Project Management for the Acquisition of Capital Assets",
        "PDFDocName" : "o413.3b-chg6-ltdchg.pdf",
        "CTA" : "NULL",
        "Type" : "Order",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "Yes",
        "name" : "https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg6-ltdchg",
        "PDFDocLink" : "https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg6-ltdchg/@@images/file",
        "Writer" : "MFrank"
      },
      "position" : {
        "x" : -3486.7983749393024,
        "y" : -275.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8188",
        "TabStandardsInvokedStandards" : "[]",
        "Description" : "This Order implements the policy that establishes a Department-wide oversight process to protect the public, workers, environment, and national security assets effectively through continuous improvement. Supersedes DOE O 226.1A.",
        "MiscComments" : "NULL",
        "LastUpdate" : "25-Apr-11",
        "TabHistorySupersedes" : "[        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-a\"      ]",
        "TabHistorySupersededBy" : "[        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b-chg1-admchg\"      ]",
        "OPI" : "NULL",
        "IS_DOE" : "Y",
        "TabHistoryCancels" : "[]",
        "shared_name" : "https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "OPR" : "EH - Office of Environment, Health, Safety and Security",
        "TabHistoryCanceledBy" : "[]",
        "InvokingDirective" : "No",
        "TabExemptions" : "Deputy Administrator for Naval Reactors (Director) will implement and oversee requirements and practices pertaining to this Order for activities under the director's cognizance, as deemed appropriate. With respect to intelligence-related activities of the Director, Office of Intelligence and Counterintelligence , and counterintelligence-related activities of the Office of Intelligence and Counterintelligence , this Order applies only to information protection and cyber security measures pursuant to Executive Order 12333. Consistent with Secretarial Delegation Order Number 00-033.00B to the Administrator and Chief Executive Officer, Bonneville Power Administration, this Order does not apply to oversight of environmental programs or occupational safety and health programs at Bonneville Power Administration. This Order does not apply to the Office of Inspector General. Although a BPA exemption is contained in the current directive, a BPA exemption memo is attached for historical purposes.",
        "SLMOffice" : "NULL",
        "TabHistoryCertifiedBy" : "[]",
        "SUID" : 8188,
        "ID" : "DOE O 226.1B",
        "TabRelatedTo" : "[        \"https://www.directives.doe.gov/exemptions/bpa_226.1b_exemption\"      ]",
        "Subjects" : "Administration,Safety,Security",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 504,
        "ApprovedDate" : "25-Apr-11",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "[        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-EGuide-2\",        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-APolicy-b\",        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-EGuide-2a\",        \"https://www.directives.doe.gov/directives-documents/400-series/0414.1-EGuide-1C\"      ]",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "NULL",
        "DNFSB" : "NULL",
        "Title1" : "Implementation of Department of Energy Oversight Policy",
        "PDFDocName" : "o226.1b.pdf",
        "CTA" : "NULL",
        "Type" : "Order",
        "TabAssociatedDOEDirective" : "[]",
        "CRD" : "Yes",
        "name" : "https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "PDFDocLink" : "https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b/@@images/file",
        "Writer" : "kdressman"
      },
      "position" : {
        "x" : -3591.7983749393024,
        "y" : -275.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8226",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "NULL",
        "LastUpdate" : "8-May-13",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "NULL",
        "IS_DOE" : "Y",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://www.directives.doe.gov/directives-documents/400-series/0414.1-BOrder-d-admchg1",
        "OPR" : "AU - Office of Environment, Health, Safety and Security",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "Yes",
        "TabExemptions" : "NULL",
        "SLMOffice" : "NULL",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8226,
        "ID" : "DOE O 414.1D Chg 1 (Admin Chg)",
        "TabRelatedTo" : "NULL",
        "Subjects" : "Administration",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1587,
        "ApprovedDate" : "25-Apr-11",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "NULL",
        "DNFSB" : "NULL",
        "Title1" : "Quality Assurance",
        "PDFDocName" : "o414.1dAdmChg1.pdf",
        "CTA" : "NULL",
        "Type" : "Order",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "Yes",
        "name" : "https://www.directives.doe.gov/directives-documents/400-series/0414.1-BOrder-d-admchg1",
        "PDFDocLink" : "https://www.directives.doe.gov/directives-documents/400-series/0414.1-BOrder-d-admchg1/@@images/file",
        "Writer" : "CPalay"
      },
      "position" : {
        "x" : -3906.7983749393024,
        "y" : -275.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8238",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "NULL",
        "LastUpdate" : "17-Jan-17",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "NULL",
        "IS_DOE" : "Y",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://www.directives.doe.gov/directives-documents/200-series/0251.001-BOrder-d",
        "OPR" : "MA - Office of Management",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "No",
        "TabExemptions" : "NULL",
        "SLMOffice" : "NULL",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8238,
        "ID" : "DOE O 251.1D",
        "TabRelatedTo" : "NULL",
        "Subjects" : "Administration",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1456,
        "ApprovedDate" : "17-Jan-17",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "NULL",
        "DNFSB" : "NULL",
        "Title1" : "Departmental Directives Program",
        "PDFDocName" : "o251.1D.pdf",
        "CTA" : "NULL",
        "Type" : "Order",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "No",
        "name" : "https://www.directives.doe.gov/directives-documents/200-series/0251.001-BOrder-d",
        "PDFDocLink" : "https://www.directives.doe.gov/directives-documents/200-series/0251.001-BOrder-d/@@images/file",
        "Writer" : "RMack"
      },
      "position" : {
        "x" : -4156.5416289075565,
        "y" : -630.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8186",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "This supplemental directive (SD) establishes the National Nuclear Security Administration (NNSA) Site Governance Model as the system that the Federal government and NNSA’s contractor partners work within to help assure effective mission performance and operational excellence. The SD supplements the requirements of Department of Energy (DOE) Policy (P) 226.1B, Department of Energy Oversight Policy and DOE Order (O) 226.1B, Implementation of DOE Oversight Policy.",
        "MiscComments" : "",
        "LastUpdate" : "",
        "TabHistorySupersedes" : "[]",
        "TabHistorySupersededBy" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c\"      ]",
        "OPI" : "Office of Safety, Infrastructure and Operations",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-a\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/20-series/nap-0021-0000\"      ]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Safety, Infrastructure and Operations",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8186,
        "ID" : "SD 226.1B",
        "TabRelatedTo" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-adm-chg1\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-adm-chg-1\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a\",        \"https://directives.nnsa.doe.gov/bop/bop-0010-0003\",        \"https://directives.nnsa.doe.gov/bop/bop-0001-0331\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/20-series/nap-0021-0000\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/20-series/nap-0021-0000\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002-recertified\"      ]",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 58,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "12-Aug-16",
        "DNFSB" : "No",
        "Title1" : "NNSA Site Governance",
        "PDFDocName" : "SD 226.1B.pdf",
        "CTA" : "Yes",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-APolicy-b\",        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b\",        \"https://www.directives.doe.gov/draft/0227.1-BOrder-A-Draft\",        \"https://www.directives.doe.gov/directives-documents/400-series/0412.1-BOrder-a-chg1-AdmChg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg2-pgchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0414.1-BOrder-d-admchg1\",        \"https://www.directives.doe.gov/directives-documents/400-series/0470.4-BOrder-b-admchg1\"      ]",
        "CRD" : "Yes",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3733.2805177964456,
        "y" : -430.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8198",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "NULL",
        "LastUpdate" : "9-Aug-16",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "NULL",
        "IS_DOE" : "Y",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://www.directives.doe.gov/directives-documents/200-series/0226.2-Apolicy",
        "OPR" : "EH - Office of Environment, Health, Safety and Security",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "No",
        "TabExemptions" : "NULL",
        "SLMOffice" : "NULL",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8198,
        "ID" : "DOE P 226.2",
        "TabRelatedTo" : "NULL",
        "Subjects" : "Administration",
        "selected" : false,
        "Status" : "Current",
        "Nr" : 1430,
        "ApprovedDate" : "9-Aug-16",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "NULL",
        "DNFSB" : "NULL",
        "Title1" : "Policy for Federal Oversight and Contractor Assurance Systems",
        "PDFDocName" : "p226.2.pdf",
        "CTA" : "NULL",
        "Type" : "Policy",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "No",
        "name" : "https://www.directives.doe.gov/directives-documents/200-series/0226.2-Apolicy",
        "PDFDocLink" : "https://www.directives.doe.gov/directives-documents/200-series/0226.2-APolicy/@@images/file",
        "Writer" : "Berta Schreiber and kdressman"
      },
      "position" : {
        "x" : -4514.0416289075565,
        "y" : -430.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8236",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "NULL",
        "LastUpdate" : "21-Dec-15",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "NULL",
        "IS_DOE" : "Y",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://www.directives.doe.gov/directives-documents/200-series/0227.1-BOrder-A",
        "OPR" : "EA - Office of Independent Enterprise Assessment",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "No",
        "TabExemptions" : "NULL",
        "SLMOffice" : "NULL",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8236,
        "ID" : "DOE O 227.1A",
        "TabRelatedTo" : "NULL",
        "Subjects" : "Administration,Safety",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1433,
        "ApprovedDate" : "21-Dec-15",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "NULL",
        "DNFSB" : "NULL",
        "Title1" : "Independent Oversight Program",
        "PDFDocName" : "o227.1A.pdf",
        "CTA" : "NULL",
        "Type" : "Order",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "Yes",
        "name" : "https://www.directives.doe.gov/directives-documents/200-series/0227.1-BOrder-A",
        "PDFDocLink" : "https://www.directives.doe.gov/directives-documents/200-series/0227.1-BOrder-A/@@images/file",
        "Writer" : "ENicoll"
      },
      "position" : {
        "x" : -4051.5416289075565,
        "y" : -630.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8210",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "Canceled by SD 226.1C, NNSA Site Governance, dated 10-1-2019.",
        "LastUpdate" : "",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "Office of Nuclear Safety & Governance",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://directives.nnsa.doe.gov/bop/bop-0010-0003",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Defense Programs",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8210,
        "ID" : "BOP 10.003",
        "TabRelatedTo" : "NULL",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1210,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "18-Jan-12",
        "DNFSB" : "Yes",
        "Title1" : "Site Integrated Assessment Plan (SIAP) Development",
        "PDFDocName" : "BOP 10.003.pdf",
        "CTA" : "Yes",
        "Type" : "Business Operating Procedure (BOP)",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/bop/bop-0010-0003",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/bop/bop-0010-0003/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3801.7983749393024,
        "y" : -275.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8184",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "This Supplemental Directive establishes the requirements, processes, and procedures for conducting biennial reviews under the National Nuclear Security Administration (NNSA) Chief of Defense Nuclear Safety (CDNS). The CDNS is responsible for maintaining operational awareness of nuclear safety performance of NNSA Headquarters, Site Offices and contractors on behalf of the Central Technical Authority and Administrator. One of the means by which CDNS maintains this awareness is through biennial and other types of reviews.",
        "MiscComments" : "",
        "LastUpdate" : "",
        "TabHistorySupersedes" : "[]",
        "TabHistorySupersededBy" : "[]",
        "OPI" : "Office of the Chief of Defense Nuclear Safety",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b\"      ]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Defense Nuclear Security",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8184,
        "ID" : "SD 226.1-1A",
        "TabRelatedTo" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c\"      ]",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 70,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "16-Dec-11",
        "DNFSB" : "Yes",
        "Title1" : "Headquarters Biennial Review of Nuclear Safety Performance",
        "PDFDocName" : "SD 226.1-1A Biennial Review_0.pdf",
        "CTA" : "Yes",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b\",        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-APolicy-b\"      ]",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3723.497184463112,
        "y" : -630.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8222",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "NULL",
        "LastUpdate" : "21-May-14",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "NULL",
        "IS_DOE" : "Y",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://www.directives.doe.gov/directives-documents/400-series/0412.1-BOrder-a-chg1-AdmChg",
        "OPR" : "MA - Office of Management",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "No",
        "TabExemptions" : "NULL",
        "SLMOffice" : "NULL",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8222,
        "ID" : "DOE O 412.1A Chg 1 (AdminChg)",
        "TabRelatedTo" : "NULL",
        "Subjects" : "Administration",
        "selected" : false,
        "Status" : "Current",
        "Nr" : 1538,
        "ApprovedDate" : "21-Apr-05",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "NULL",
        "DNFSB" : "NULL",
        "Title1" : "Work Authorization System",
        "PDFDocName" : "412.1chg1-adminchg.pdf",
        "CTA" : "NULL",
        "Type" : "Order",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "No",
        "name" : "https://www.directives.doe.gov/directives-documents/400-series/0412.1-BOrder-a-chg1-AdmChg",
        "PDFDocLink" : "https://www.directives.doe.gov/directives-documents/400-series/0412.1-BOrder-a-chg1-AdmChg/@@images/file",
        "Writer" : "Attila Csoma"
      },
      "position" : {
        "x" : -3696.7983749393024,
        "y" : -275.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8196",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "This Supplemental Directive (SD) documents National Nuclear Security Administration (NNSA) roles and responsibilities in implementing safety management systems. To ensure that work is performed safely, this SD defines, identifies, and clarifies the NNSA safety management functions, responsibilities, authorities, and associated delegations within program and functional management organizations and field offices. Supersedes SD 450.2A, dated 10-20-17.",
        "MiscComments" : "",
        "LastUpdate" : "23-Apr-21",
        "TabHistorySupersedes" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a\"      ]",
        "TabHistorySupersededBy" : "[]",
        "OPI" : "Office of Safety, Infrastructure and Operations",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Safety, Infrastructure and Operations",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8196,
        "ID" : "SD 450.2B",
        "TabRelatedTo" : "[        \"https://directives.nnsa.doe.gov/bop/bop-0413-008\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-1\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0360-001a\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0426-0001\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0401-001\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0442.001\",        \"https://directives.nnsa.doe.gov/nnsa-policy-documents/500-series/nap-0540-003\"      ]",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Current",
        "Nr" : 23,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "23-Apr-21",
        "DNFSB" : "No",
        "Title1" : "Functions, Responsibilities, and Authorities (FRA) for Safety Management",
        "PDFDocName" : "SD_450.2B_4-23-21.pdf",
        "CTA" : "No",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[        \"https://www.directives.doe.gov/directives-documents/400-series/0450.2-BOrder-chg1-MinChg\",        \"https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b\",        \"https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg6-ltdchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0435.1-BOrder-chg2-AdminChg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0435.1-DManual-1-chg3-ltdchg-1\",        \"https://www.directives.doe.gov/directives-documents/400-series/0458.1-border-chg4-ltdchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0433.1-BOrder-b-chg1-AdmChg\",        \"https://www.directives.doe.gov/directives-documents/100-series/0151.1-BOrder-d-chg1-minchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0426.2-BOrder-chg1-admchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0425.1-BOrder-d-chg2-minchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0422.1-BOrder-chg3-minchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0414.1-border-d-ltdchg2\",        \"https://www.directives.doe.gov/directives-documents/400-series/0440.1-border-b-chg3-ltdchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0420.1-BOrder-C-chg3-ltdchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0410.1-BOrder\",        \"https://www.directives.doe.gov/directives-documents/400-series/0460.1-BOrder-D\",        \"https://www.directives.doe.gov/directives-documents/400-series/0461.1-BOrder-c-chg1-minchg\",        \"https://www.directives.doe.gov/directives-documents/400-series/0452.1-BOrder-e\",        \"https://www.directives.doe.gov/directives-documents/100-series/0153.1-BOrder\",        \"https://www.directives.doe.gov/directives-documents/400-series/0426.1-BOrder-b\",        \"https://www.directives.doe.gov/directives-documents/400-series/0450.4-EGuide-1c\"      ]",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3558.0483749393024,
        "y" : -430.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8388",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "To establish the requirements and describe the processes for conducting Project Reviews on active projects executed by the National Nuclear Security Administration (NNSA). Cancels BOP 413.4, dated 11-18-2014.",
        "MiscComments" : "",
        "LastUpdate" : "10-May-21",
        "TabHistorySupersedes" : "[]",
        "TabHistorySupersededBy" : "[]",
        "OPI" : "Office of Acquisition & Project Management",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[        \"https://directives.nnsa.doe.gov/bop/bop-0413-004\"      ]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0413-0003-1",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Acquisition & Project Management",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8388,
        "ID" : "SD 413.3-1",
        "TabRelatedTo" : "[]",
        "NNSA_Related" : true,
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Current",
        "Nr" : 22,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "1",
        "IssueDate" : "10-May-21",
        "DNFSB" : "No",
        "Title1" : "Project Reviews",
        "PDFDocName" : "SD 413.3-1_20210511.pdf",
        "CTA" : "No",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[        \"https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg6-ltdchg\"      ]",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0413-0003-1",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0413-0003-1/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3400.5483749393024,
        "y" : -430.08012757286406
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8234",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "NULL",
        "MiscComments" : "Renumbers NAP-33, Planning, Programming, Budgeting, and Evaluation (PPBE) Process, dated 1-17-2017.",
        "LastUpdate" : "",
        "TabHistorySupersedes" : "NULL",
        "TabHistorySupersededBy" : "NULL",
        "OPI" : "Office of Planning, Programming, Budget & Evaluation",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "NULL",
        "shared_name" : "https://directives.nnsa.doe.gov/nnsa-policy-documents/100-series/nap-0130-001",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "NULL",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Management & Budget",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8234,
        "ID" : "NAP 130.1",
        "TabRelatedTo" : "NULL",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 1235,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "NULL",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "17-Jan-17",
        "DNFSB" : "No",
        "Title1" : "Planning",
        "PDFDocName" : "NAP 130.1.pdf",
        "CTA" : "No",
        "Type" : "NNSA Policy (NAP)",
        "TabAssociatedDOEDirective" : "NULL",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/nnsa-policy-documents/100-series/nap-0130-001",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/nnsa-policy-documents/100-series/nap-0130-001/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3946.5416289075565,
        "y" : -630.0801275728641
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "8194",
        "TabStandardsInvokedStandards" : "NULL",
        "Description" : "Define, identify, and clarify the National Nuclear Security Administration (NNSA) safety management functions, responsibilities, authorities, and associated delegations within program and functional management organizations, and field offices, to ensure that work is performed safely. This Supplemental Directive (SD) documents NNSA roles and responsibilities in implementing safety management systems.",
        "MiscComments" : "",
        "LastUpdate" : "4-Jul-18",
        "TabHistorySupersedes" : "[]",
        "TabHistorySupersededBy" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b\"      ]",
        "OPI" : "Office of Safety, Infrastructure and Operations",
        "IS_DOE" : "N",
        "TabHistoryCancels" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-adm-chg1\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0004-1\"      ]",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a",
        "OPR" : "NULL",
        "TabHistoryCanceledBy" : "[]",
        "InvokingDirective" : "NULL",
        "TabExemptions" : "NULL",
        "SLMOffice" : "Office of Safety, Infrastructure and Operations",
        "TabHistoryCertifiedBy" : "NULL",
        "SUID" : 8194,
        "ID" : "SD 450.2A",
        "TabRelatedTo" : "[        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c\",        \"https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b\"      ]",
        "Subjects" : "NULL",
        "selected" : false,
        "Status" : "Archive",
        "Nr" : 35,
        "ApprovedDate" : "NULL",
        "TabHistoryRenumberedTo" : "[]",
        "TabRelatedRelatedFrom" : "NULL",
        "NNSA_Related_Type" : "2",
        "IssueDate" : "4-Jul-18",
        "DNFSB" : "No",
        "Title1" : "Functions, Responsibilities, and Authorities (FRA) for Safety Management",
        "PDFDocName" : "SD 450.2A Final.pdf",
        "CTA" : "No",
        "Type" : "Supplemental Directive (SD)",
        "TabAssociatedDOEDirective" : "[        \"https://www.directives.doe.gov/directives-documents/400-series/0450.2-BOrder-chg1-MinChg\"      ]",
        "CRD" : "No",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a",
        "PDFDocLink" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a/@@images/file",
        "Writer" : "NULL"
      },
      "position" : {
        "x" : -3661.622184463112,
        "y" : -1000.0801275728641
      },
      "selected" : false
    } ],
    "edges" : [ {
      "data" : {
        "id" : "11444",
        "source" : "8192",
        "target" : "8194",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a",
        "interaction" : "Related To",
        "SUID" : 11444,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11446",
        "source" : "8192",
        "target" : "8166",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "interaction" : "Related To",
        "SUID" : 11446,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11448",
        "source" : "8192",
        "target" : "8196",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "interaction" : "Related To",
        "SUID" : 11448,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11450",
        "source" : "8192",
        "target" : "8188",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11450,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11452",
        "source" : "8192",
        "target" : "8198",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.2-Apolicy",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.2-Apolicy",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11452,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11454",
        "source" : "8192",
        "target" : "8184",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (History Cancels) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b (History Cancels) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a",
        "interaction" : "History Cancels",
        "SUID" : 11454,
        "shared_interaction" : "History Cancels",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11560",
        "source" : "8230",
        "target" : "8166",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "interaction" : "Related To",
        "SUID" : 11560,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11562",
        "source" : "8230",
        "target" : "8196",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "interaction" : "Related To",
        "SUID" : 11562,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11326",
        "source" : "8166",
        "target" : "8184",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a",
        "interaction" : "Related To",
        "SUID" : 11326,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11328",
        "source" : "8166",
        "target" : "8230",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a",
        "interaction" : "Related To",
        "SUID" : 11328,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11330",
        "source" : "8166",
        "target" : "8194",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a",
        "interaction" : "Related To",
        "SUID" : 11330,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11332",
        "source" : "8166",
        "target" : "8216",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002",
        "interaction" : "Related To",
        "SUID" : 11332,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11334",
        "source" : "8166",
        "target" : "8232",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/bop/bop-0413-007",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/bop/bop-0413-007",
        "interaction" : "Related To",
        "SUID" : 11334,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11336",
        "source" : "8166",
        "target" : "8234",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/nnsa-policy-documents/100-series/nap-0130-001",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/nnsa-policy-documents/100-series/nap-0130-001",
        "interaction" : "Related To",
        "SUID" : 11336,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11338",
        "source" : "8166",
        "target" : "8164",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0205-0001a",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0205-0001a",
        "interaction" : "Related To",
        "SUID" : 11338,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11340",
        "source" : "8166",
        "target" : "8192",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "interaction" : "Related To",
        "SUID" : 11340,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11342",
        "source" : "8166",
        "target" : "8196",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "interaction" : "Related To",
        "SUID" : 11342,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11344",
        "source" : "8166",
        "target" : "8198",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.2-Apolicy",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.2-Apolicy",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11344,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11346",
        "source" : "8166",
        "target" : "8188",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11346,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11348",
        "source" : "8166",
        "target" : "8236",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0227.1-BOrder-A",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0227.1-BOrder-A",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11348,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11350",
        "source" : "8166",
        "target" : "8238",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0251.001-BOrder-d",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0251.001-BOrder-d",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11350,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11352",
        "source" : "8166",
        "target" : "8222",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0412.1-BOrder-a-chg1-AdmChg",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0412.1-BOrder-a-chg1-AdmChg",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11352,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11354",
        "source" : "8166",
        "target" : "8240",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-B-chg5-minchg",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-B-chg5-minchg",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11354,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11356",
        "source" : "8166",
        "target" : "8226",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0414.1-BOrder-d-admchg1",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0414.1-BOrder-d-admchg1",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11356,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11358",
        "source" : "8166",
        "target" : "8186",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (History Supersedes) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (History Supersedes) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b",
        "interaction" : "History Supersedes",
        "SUID" : 11358,
        "shared_interaction" : "History Supersedes",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11360",
        "source" : "8166",
        "target" : "8210",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (History Cancels) https://directives.nnsa.doe.gov/bop/bop-0010-0003",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (History Cancels) https://directives.nnsa.doe.gov/bop/bop-0010-0003",
        "interaction" : "History Cancels",
        "SUID" : 11360,
        "shared_interaction" : "History Cancels",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11362",
        "source" : "8166",
        "target" : "8242",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (History Superseded By) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c (History Superseded By) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d",
        "interaction" : "History Superseded By",
        "SUID" : 11362,
        "shared_interaction" : "History Superseded By",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11568",
        "source" : "8242",
        "target" : "8198",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.2-Apolicy",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.2-Apolicy",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11568,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11572",
        "source" : "8242",
        "target" : "8166",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d (History Supersedes) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001d (History Supersedes) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "interaction" : "History Supersedes",
        "SUID" : 11572,
        "shared_interaction" : "History Supersedes",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11320",
        "source" : "8164",
        "target" : "8166",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0205-0001a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0205-0001a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "interaction" : "Related To",
        "SUID" : 11320,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11396",
        "source" : "8186",
        "target" : "8184",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a",
        "interaction" : "Related To",
        "SUID" : 11396,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11398",
        "source" : "8186",
        "target" : "8210",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Related To) https://directives.nnsa.doe.gov/bop/bop-0010-0003",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Related To) https://directives.nnsa.doe.gov/bop/bop-0010-0003",
        "interaction" : "Related To",
        "SUID" : 11398,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11404",
        "source" : "8186",
        "target" : "8216",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Related To) https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Related To) https://directives.nnsa.doe.gov/nnsa-policy-documents/400-series/nap-0413-002",
        "interaction" : "Related To",
        "SUID" : 11404,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11410",
        "source" : "8186",
        "target" : "8188",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11410,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11414",
        "source" : "8186",
        "target" : "8222",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0412.1-BOrder-a-chg1-AdmChg",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0412.1-BOrder-a-chg1-AdmChg",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11414,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11418",
        "source" : "8186",
        "target" : "8226",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0414.1-BOrder-d-admchg1",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0414.1-BOrder-d-admchg1",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11418,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11426",
        "source" : "8186",
        "target" : "8166",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (History Superseded By) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b (History Superseded By) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "interaction" : "History Superseded By",
        "SUID" : 11426,
        "shared_interaction" : "History Superseded By",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11382",
        "source" : "8184",
        "target" : "8186",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-b",
        "interaction" : "Related To",
        "SUID" : 11382,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11384",
        "source" : "8184",
        "target" : "8166",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "interaction" : "Related To",
        "SUID" : 11384,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11386",
        "source" : "8184",
        "target" : "8188",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11386,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11390",
        "source" : "8184",
        "target" : "8192",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a (History Canceled By) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1a (History Canceled By) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "interaction" : "History Canceled By",
        "SUID" : 11390,
        "shared_interaction" : "History Canceled By",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11482",
        "source" : "8196",
        "target" : "8194",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (History Supersedes) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (History Supersedes) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a",
        "interaction" : "History Supersedes",
        "SUID" : 11482,
        "shared_interaction" : "History Supersedes",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11486",
        "source" : "8196",
        "target" : "8192",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "interaction" : "Related To",
        "SUID" : 11486,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11492",
        "source" : "8196",
        "target" : "8188",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/200-series/0226.1-BOrder-b",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11492,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11494",
        "source" : "8196",
        "target" : "8380",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg6-ltdchg",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg6-ltdchg",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11494,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11468",
        "source" : "8196",
        "target" : "8166",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "interaction" : "Related To",
        "SUID" : 11468,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11470",
        "source" : "8196",
        "target" : "8230",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0251-0001-a",
        "interaction" : "Related To",
        "SUID" : 11470,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11808",
        "source" : "8388",
        "target" : "8380",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0413-0003-1 (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg6-ltdchg",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0413-0003-1 (Associated DOE Directive) https://www.directives.doe.gov/directives-documents/400-series/0413.3-BOrder-b-chg6-ltdchg",
        "interaction" : "Associated DOE Directive",
        "SUID" : 11808,
        "shared_interaction" : "Associated DOE Directive",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11810",
        "source" : "8388",
        "target" : "8370",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0413-0003-1 (History Cancels) https://directives.nnsa.doe.gov/bop/bop-0413-004",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0413-0003-1 (History Cancels) https://directives.nnsa.doe.gov/bop/bop-0413-004",
        "interaction" : "History Cancels",
        "SUID" : 11810,
        "shared_interaction" : "History Cancels",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11456",
        "source" : "8194",
        "target" : "8166",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001c",
        "interaction" : "Related To",
        "SUID" : 11456,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11458",
        "source" : "8194",
        "target" : "8192",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a (Related To) https://directives.nnsa.doe.gov/supplemental-directive/sd-0226-0001-1b",
        "interaction" : "Related To",
        "SUID" : 11458,
        "shared_interaction" : "Related To",
        "selected" : false
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "11466",
        "source" : "8194",
        "target" : "8196",
        "shared_name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a (History Superseded By) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "name" : "https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-a (History Superseded By) https://directives.nnsa.doe.gov/supplemental-directive/sd-0450-0002-b",
        "interaction" : "History Superseded By",
        "SUID" : 11466,
        "shared_interaction" : "History Superseded By",
        "selected" : false
      },
      "selected" : false
    } ]
  }
}}